name: Build

on: workflow_dispatch

jobs:
  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --prefix=cstrike --build-games=cstrike --disable-warns
        ./waf.bat build
        ./waf.bat install
    - uses: actions/upload-artifact@v4.4.3
    - name: Upload a Build Artifact
      with:
        path: ./
