name: Build

on: workflow_dispatch

jobs:
  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --prefix=hl2 --build-games=hl2 --disable-warns
        ./waf.bat build
